cat > .github/workflows/backend-deploy.yml << 'EOF'
name: Backend CI/CD

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run linting
        working-directory: ./backend
        run: npm run lint || echo "Linting not configured yet"

      - name: Build
        working-directory: ./backend
        run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v4
      - name: Deployment placeholder
        run: echo "Ready to deploy backend"
EOF
